Release: slate-admin v2.1.25
SlateFoundation/slate-admin pull request #130
Opened 2016-12-15 01:44 UTC by nbey

- Unify Section Term Reports with Section Interim Reports

2016-12-15 19:36 UTC, themightychris commented
@nbey this PR is setup to merge a feature into `develop`, it's not a release PR

2016-12-15 19:37 UTC, nbey commented
Ok, i'll rename it, and create a new PR accordingly.

2016-12-20 18:21 UTC, themightychris requested changes
@nbey the interims section also needs section note loading/saving implemented.

It looks like the interims controller has a bunch of incomplete nonfunctional code towards managing section notes that appears to be have copied from the old Narratives controller, which demonstrates the preferred way to load/save individual models: https://github.com/SlateFoundation/slate-admin/blob/3748ef3a2234a1d7ed69092bb7f6fa3ad54512da/sencha-workspace/SlateAdmin/app/controller/progress/Narratives.js#L184

Why did you remove the individual model loading/saving in favor of using a store?

Also, there is some feedback that needs to be addressed in SlateFoundation/slate-core-data#4 -- please push commits there and bump the submodule version in this PR

2016-12-20 18:21 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/model/course/SectionTermData.js
> +            name: "ID",
@nbey replace all these double quotes with single quotes, your linter should be warning about this if it is configured correctly

2016-12-20 18:21 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/controller/progress/terms/Report.js
> +        'courses.SectionTermData'
@nbey a store should not be used for loading/saving a single record, only managing a population of records. Use the static `.load()` method on the model to make a request to load an individual model without a store. I believe you can pass null for id and then use the options param to pass arbitrary params for the load request.

2016-12-21 01:39 UTC, nbey commented
@themightychris Could you check out the latest commits I made?

2016-12-22 16:00 UTC, themightychris requested changes
comments left for interims probably apply equally for terms

2016-12-22 16:00 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/controller/progress/interims/Report.js
> +        SectionNotesModel.getProxy().createOperation('read', {
@nbey this name needs updating to `SectionTermDataModel`

2016-12-22 16:00 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/controller/progress/interims/Report.js
> +                        CourseSectionID: section.getId()
@nbey creating new section notes does not work currently...below on line 351 we're getting `sectionDataRecord.get('SectionID')` and aborting if it doesn't resolve to a section, but here we're setting `sectionNotes.get('CourseSectionID')`

2016-12-22 16:00 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/controller/progress/interims/Report.js
> +            sectionDataRecord = sectionNotesForm.getRecord(),
@nbey rename to `sectionTermDataRecord` throughout for consistency, these models can get pretty confusing to follow if we're not absolutely consistent with naming them

2016-12-22 16:00 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/controller/progress/interims/Report.js
> +            callback: function(sectionData, operation, success) {
@nbey call this `savedSectionTermDataRecord`. It should be the same instance as `sectionTermDataRecord` but we need to receive the param and linters don't like the same variable being redeclared. Theoretically the save method COULD return a new model instance, so all the code within this callback should use the potentially-new `saved*` instance reference

2016-12-22 16:03 UTC, themightychris commented on sencha-workspace/SlateAdmin/app/view/progress/SectionNotesForm.js
>  /*jslint browser: true, undef: true, white: false, laxbreak: true *//*global Ext,Slate*/
@nbey strip this jslint config

2016-12-22 16:06 UTC, themightychris commented
@nbey one last thing, let's add responsibilities overviews to each of the progress interims/terms controllers like these have:

- https://github.com/JarvusInnovations/spark-classroom/blob/develop/sencha-workspace/SparkClassroomTeacher/app/controller/Viewport.js
- https://github.com/JarvusInnovations/spark-classroom/blob/develop/sencha-workspace/SparkClassroomTeacher/app/controller/Work.js

2016-12-29 20:12 UTC, merged